#!/bin/sh

#. ${portz_libdir}/scripts/defs.sh

if [ "$OSTYPE" == "msys" ] ; then 
    portz_invoke "patch -p1 < ${package_folder}/gcc-no-ansi.patch"
    portz_invoke "patch -p0 < ${package_folder}/mingw-configure.patch"
fi
